### ISSUE TITLE
ID review

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/guide-openliberty-operator-openshift#10]
ID edit suggestions in #9 

I made edits to the "other parameters" section like we made for the Kubernetes operator guide. Similarly if any edits are made there to address the following comment, they should be made to this guide as well:

>  it's not clear what to look for when you "visit the microservice" in this section, since the browser just shows unformatted config. How is this result different than the one ion the previous section? What might a user look for as confirmation that the Operator successfully implemented the health checks?

**Comment by gkwan-ibm** [comment]
At the "Specifying optional parameters" section,
- add instructions to run `kubectl describe pods` after `kubectl apply -f deploy.yaml`
   - cloud-hosted run `kubectl describe pods | grep health`   
- will see the following lines in the output
```
    Liveness:     http-get http://:9080/health/live delay=30s timeout=10s period=2s #success=1 #failure=12
    Readiness:    http-get http://:9080/health/ready delay=30s timeout=10s period=2s #success=1 #failure=12
    Startup:      http-get http://:9080/health/started delay=30s timeout=10s period=2s #success=1 #failure=12
```

**Comment by gkwan-ibm** [comment]
close
- the guide was updated as https://github.com/OpenLiberty/guide-openliberty-operator-openshift/issues/10#issuecomment-1149103914
