### ISSUE TITLE
Update the cloud-hosted guide to use OL operator 1.2.1 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-openliberty-operator-openshift#33]
The static guide already updated. This issue will update the cloud hosted guide to use OL operator 1.2.1
  - pending on https://github.ibm.com/skills-network/labs/issues/1811

Ref:
  - https://github.com/OpenLiberty/open-liberty-operator/tree/main/deploy/releases/1.2.1/kubectl#installation

**Comment by leochr** [comment]
OL operator 1.2.1 is now available: https://github.com/OpenLiberty/open-liberty-operator/tree/main/deploy/releases/1.2.1

**Comment by gkwan-ibm** [comment]
updated the title and description

**Comment by gkwan-ibm** [comment]
close
- the cloud-hosted guide and SNL was updated to use OL operator 1.2.1
