### ISSUE TITLE
Update the link to operator install document

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/guide-openliberty-operator-openshift#35]
The skills network instructions include the following:

_In this Skill Network enviornment, the Open Liberty Operator is already installed by the administrator. If you like to learn how to install the Open Liberty Operator, you can learn from the [Deploying microservices to OpenShift by using Kubernetes Operators](https://openliberty.io/guides/cloud-openshift-operator.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkGuidedProjectscloudhostedguideopenlibertyoperatoropenshift366-2023-01-01#installing-the-operators) guide or the Open Liberty Operator [document](https://github.com/OpenLiberty/open-liberty-operator/blob/master/deploy/releases/0.7.1/readme.adoc)._

The last link is pointing to an older version of the operator. Instead, it should point to this: 
https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1.adoc#operator-installation

**Comment by leochr** [comment]
fyi @gkwan-ibm

**Comment by gkwan-ibm** [comment]
close
- the issue was addressed
